repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: hatch run lint:all
        stages: [commit]
        language: system
        require_serial: true

      - id: check-added-large-files
        name: Check for added large files
        entry: hatch run check-added-large-files
        language: system

      - id: check-toml
        name: Check Toml
        entry: hatch run check-toml
        language: system
        types: [toml]

      - id: check-yaml
        name: Check Yaml
        entry: hatch run check-yaml
        language: system
        types: [yaml]

      - id: end-of-file-fixer
        name: Fix End of Files
        entry: hatch run end-of-file-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]

      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: hatch run trailing-whitespace-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]
