repos:
  - repo: local
    hooks:
      - id: flake8
        name: Flake8 linting
        entry: hatch run lint:flake8
        types: [python]
        language: system
        require_serial: true

      - id: ufmt
        name: Î¼fmt code formatter check (black + usort)
        entry: hatch run lint:ufmt check
        type: [python]
        language: system
        require_serial: true

      - id: typing
        name: Mypy type checking
        entry: hatch run lint:typing
        type: [python]
        language: system
        require_serial: true

      - id: check-added-large-files
        name: Check for added large files
        entry: hatch run lint:check-added-large-files
        language: system

      - id: check-toml
        name: Check Toml
        entry: hatch run lint:check-toml
        language: system
        types: [toml]

      - id: check-yaml
        name: Check Yaml
        entry: hatch run lint:check-yaml
        language: system
        types: [yaml]

      - id: end-of-file-fixer
        name: Fix End of Files
        entry: hatch run lint:end-of-file-fixer
        language: system
        types: [text]

      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: hatch run lint:trailing-whitespace-fixer
        language: system
        types: [text]
